name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish-tauri:
    permissions:
      contents: write
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v6
        with:
          version: 10

      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: pnpm

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Generate Cargo.lock
        working-directory: ./src-tauri
        run: cargo generate-lockfile

      - uses: swatinem/rust-cache@v2
        with:
          workspaces: ./src-tauri -> target
          key: windows-latest-x86_64-pc-windows-msvc

      - name: Install frontend dependencies
        run: pnpm install --frozen-lockfile

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tauriScript: pnpm tauri
          args: --target x86_64-pc-windows-msvc

      - name: Copy portable exe
        run: |
          Copy-Item "src-tauri/target/x86_64-pc-windows-msvc/release/terax.exe" -Destination "Terax-portable-x64.exe"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Terax-portable-x64
          path: Terax-portable-x64.exe
          retention-days: 30
